# Generated by Django 6.1.1 on 2026-09-28 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAvenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_avenca_senado', models.CharField(db_index=True, max_length=50)),
                ('texto', models.TextField()),
                ('data_controle_interna', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('foi_editado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_avencas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
